version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API port
      - "9090:9090"  # MinIO Console UI
    environment:
      MINIO_ROOT_USER: adminadmin
      MINIO_ROOT_PASSWORD: adminadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

volumes:
  minio_data: