version: '3.9'

networks:
  java-api:
    external: true

services:
  java-api:
    image: java-api:1.0
    container_name: java-api
    restart: always
    environment:
      JAVA_OPTS: "-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    ports:
      - "8080:8080"
    networks:
      - java-api
#    volumes:
#      - ./certificate.crt:/tmp/certificate.crt  # Mount the certificate file
#      - ./entrypoint.sh:/etc/entrypoint.sh  # Mount the entrypoint script
#    entrypoint: ["/bin/bash", "-c", "/etc/entrypoint.sh && exec java -jar /app/app.jar"]
